volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}


services:
  django:
    image: dmvaled/wm_test_django:latest
    volumes:
      - production_django_media:/app/wm_test/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    image: dmvaled/wm_test_postgres:latest
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    image: dmvaled/wm_test_traefik:latest
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '80:80'

  redis:
    image: redis:6

  nginx:
    image: dmvaled/wm_test_nginx:latest
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
