services:
  docs:
    image: wm_test_local_docs
    container_name: wm_test_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./wm_test:/app/wm_test:z
    ports:
      - '9000:9000'
    command: /start-docs
