log:
  level: INFO

entryPoints:
  web:
    address: ':80'

http:
  routers:
    web-router:
      rule: 'Host(`localhost`) || Host(`127.0.0.1`)'
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django

    web-media-router:
      rule: '(Host(`localhost`) || Host(`127.0.0.1`)) && PathPrefix(`/media/`)'
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django-media

  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: [ 'X-CSRFToken' ]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
